### PR TITLE
Some more tweaks

### PR DESCRIPTION
**Pull request by dakkar**
* the dockerfile was missing a package
* I've added to the README: instructions on how to use Docker, and links to the various chats / forums

### CODE REVIEW

**Comment by Dil3mm4** [comment]
Furthermore, IMHO you should separate the syncing routines and the actual build routines.
Or just ask for user input to know if he wants to sync up sources again. 
Using the script multiple times with sync routines (don't ask me how) breaks default.xml somehow.

**Comment by dakkar** [comment]
I completely agree with you, @Dil3mm4. And even when things don't break, they're just very slow, because we end up doing useless work. I just don't know enough about `repo` to change how things work. These notes and the build script are mainly "stuff I tried that worked" ☺

**Comment by Dil3mm4** [comment]
Also, the stuff about resyncing/cleaning on the device tree deletes any modifications done by the user (e.g. new .mk that are not already in the upstream or any other mods done over other files), that should be avoided as well and could be "delegate" on the syncying stuff side.

(p.s. any chance that you were on Azzurra/Simosnap network over 0x90?)

**Comment by dakkar** [comment]
@Dil3mm4 I suggest we move this discussion to an issue, since it has nothing to do with this particular PR

**Comment by Dil3mm4** [comment]
https://github.com/phhusson/treble_experimentations/issues/80

**Pull request merged**
