### PR TITLE
Update to android 8.1.0_r67

### PR DESCRIPTION
**Pull request by Displax**

### CODE REVIEW

**Comment by phhusson** [comment]
Yeah well r67 is said to still be june security patch at https://source.android.com/setup/start/build-numbers, so...

**Comment by Displax** [comment]
Yep, but it contains other fixes, so...

**Comment by Githubwoman** [comment]
Will there be an updated version of GSI 8.1.0 with September security patch level?

**Comment by phhusson** [comment]
Maybe. The issue is that r67/r68 are really simply r1 with security patches
(the security patch level isn't properly set in that tag!), while r66 had
many fixes.
So before, I could just take aosp git repo, for the repo that I didn't
change,  but now I need to have my own repo for every repo in the manifest,
and meets r68 into r66.
Honestly I think there could be a full project dedicated to keeping old
aosp up and running.

Le dim. 8 sept. 2019 à 11:31, Githubwoman <notifications@github.com> a
écrit :

**Comment by Githubwoman** [comment]
Sorry, I thought that it will require only updating source code and recompiling. If it is so much work then I'm not sure if it is worth.

**Pull request closed without merging**
