### PR TITLE
build-dakkar.sh: Detect if choice and clean variable was set & bump android 10 tag

### PR DESCRIPTION
**Pull request by daniml3**
This can be useful for using services like Jenkins so you can set the variable to decide if sync or no before.
Bumped android 10 tag to r25

### CODE REVIEW

**Comment by phhusson** [comment]
I'm okay with this only if you rename the variable. "choice" has a pretty high chance of collision...
(I'll accept other solutions, like passing this as argument)

**Comment by daniml3** [comment]
I've changed the variable name, now I don't think there will be conflicts.

**Comment by daniml3** [comment]
Wew wait a second just noticed there is a clean variable. Can I do the same with it and update the pull request?

**Comment by phhusson** [comment]
Sure

**Comment by daniml3** [comment]
Done, if you're ok with merging the pull request all is ok with the code(I think).

**Comment by daniml3** [comment]
Just saw a typo error, fixed

**Pull request merged**
